### ISSUE TITLE
Another Spotify client for GNOME

### ISSUE THREAD

**Issue by janbrummer** [dann-merlin/Spotipyne#19]
Sorry for using a ticket for this, but there are no contact information anywhere in this repo:

There is now a second app featuring Spotify for GNOME: https://github.com/xou816/spot

Maybe it is worth to join forces?

**Comment by dann-merlin** [comment]
Hey, no worries. I added an email for contacting me at the end of the readme now.
Thanks for showing me! However spotipyne is more of a project for me to learn python and get a spotify app for my pinephone. Both don't appear to be a focus of this project.

Also, the two applications function in different ways, as spotipyne is using the web api and spot is using the librespot library. Meaning that spotipyne is more of a remote for spotify speakers and spot is more of a full blown client. And i kind of prefer the web api approach.

But I'll definitely be able to get some help from their GUI code as soon as I have the  time to work on spotipyne some more again.

**Comment by janbrummer** [comment]
Thanks. Spot will also address the Smartphone task (see issue tab) and will also offer remote control for other devices. So except your will to improve your Python skills the goals are the same.
